# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Python Scripts\design.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(668, 316)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(11, 11, 651, 291))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_StartDate = QtWidgets.QLabel(self.groupBox)
        self.label_StartDate.setObjectName("label_StartDate")
        self.horizontalLayout_3.addWidget(self.label_StartDate)
        self.lineEdit_StartDate = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_StartDate.setObjectName("lineEdit_StartDate")
        self.horizontalLayout_3.addWidget(self.lineEdit_StartDate)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_StopDate = QtWidgets.QLabel(self.groupBox)
        self.label_StopDate.setObjectName("label_StopDate")
        self.horizontalLayout_2.addWidget(self.label_StopDate)
        self.lineEdit_StopDate = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_StopDate.setObjectName("lineEdit_StopDate")
        self.horizontalLayout_2.addWidget(self.lineEdit_StopDate)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(9)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_chooseReport = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_chooseReport.setObjectName("pushButton_chooseReport")
        self.horizontalLayout.addWidget(self.pushButton_chooseReport)
        self.lineEdit_ReconReport = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_ReconReport.setObjectName("lineEdit_ReconReport")
        self.horizontalLayout.addWidget(self.lineEdit_ReconReport)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_email = QtWidgets.QLabel(self.groupBox)
        self.label_email.setObjectName("label_email")
        self.horizontalLayout_5.addWidget(self.label_email)
        self.lineEdit_email = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.horizontalLayout_5.addWidget(self.lineEdit_email)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_password = QtWidgets.QLabel(self.groupBox)
        self.label_password.setObjectName("label_password")
        self.horizontalLayout_6.addWidget(self.label_password)
        self.lineEdit_password = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.horizontalLayout_6.addWidget(self.lineEdit_password)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_startApp = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_startApp.setObjectName("pushButton_startApp")
        self.horizontalLayout_4.addWidget(self.pushButton_startApp)
        self.exit_button = QtWidgets.QPushButton(self.groupBox)
        self.exit_button.setObjectName("exit_button")
        self.horizontalLayout_4.addWidget(self.exit_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.label_StartDate.setText(_translate("MainWindow", "Start Date (MM/DD/YYYY)"))
        self.label_StopDate.setText(_translate("MainWindow", "Stop Date (MM/DD/YYYY)"))
        self.pushButton_chooseReport.setText(_translate("MainWindow", "Choose Reconciliation Report"))
        self.label_email.setText(_translate("MainWindow", "Email Address"))
        self.label_password.setText(_translate("MainWindow", "Password"))
        self.pushButton_startApp.setText(_translate("MainWindow", "Start Application"))
        self.exit_button.setText(_translate("MainWindow", "Exit"))

